"""add onboarding tables

Revision ID: 1ace71fc4600
Revises: 7a0e1ff89060
Create Date: 2025-11-12 18:46:40.822095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ace71fc4600'
down_revision: Union[str, None] = '7a0e1ff89060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_slug', 'teams', ['slug'], unique=False)
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=True)
    op.create_table('connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('connection_type', sa.Enum('bigquery', 'postgres', 'snowflake', name='connectiontype'), nullable=False),
    sa.Column('credentials_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('status', sa.Enum('active', 'failed', 'testing', name='connectionstatus'), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connection_status', 'connections', ['status'], unique=False)
    op.create_index('idx_connection_team', 'connections', ['team_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('fully_qualified_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('catalog_job_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('catalog_job_status', sa.Enum('pending', 'running', 'completed', 'failed', name='catalogjobstatus'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'fully_qualified_name', name='uq_dataset_fqn')
    )
    op.create_index('idx_dataset_connection', 'datasets', ['connection_id'], unique=False)
    op.create_index('idx_dataset_fqn', 'datasets', ['fully_qualified_name'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('fully_qualified_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'fully_qualified_name', name='uq_table_fqn')
    )
    op.create_index('idx_table_dataset', 'tables', ['dataset_id'], unique=False)
    op.create_index('idx_table_fqn', 'tables', ['fully_qualified_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_table_fqn', table_name='tables')
    op.drop_index('idx_table_dataset', table_name='tables')
    op.drop_table('tables')
    op.drop_index('idx_dataset_fqn', table_name='datasets')
    op.drop_index('idx_dataset_connection', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('idx_connection_team', table_name='connections')
    op.drop_index('idx_connection_status', table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.drop_index('idx_team_slug', table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
